apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-user-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: graphql-user-service
  template:
    metadata:
      labels:
        app: graphql-user-service
    spec:
      containers:
      - name: graphql-user-service
        image: gcr.io/pure-pact-428603-e7/graphql-user-service:latest
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: database-url
---
apiVersion: v1
kind: Service
metadata:
  name: graphql-user-service
spec:
  selector:
    app: graphql-user-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer