apiVersion: v1
kind: Service
metadata:
  name: graphql-user-service
spec:
  selector:
    app: graphql-user-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer