name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Diagnostic information
      run: |
        node --version
        npm --version
        cat package.json

    - name: Clean npm cache
      run: npm cache clean --force

    - name: Install dependencies
      run: npm ci --verbose
      env:
        NPM_CONFIG_LOGLEVEL: verbose

    - name: Build
      run: npm run build

    - name: Run tests
      run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - uses: actions/checkout@v3
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Install gke-gcloud-auth-plugin
      run: |
        sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates gnupg
        echo "deb https://packages.cloud.google.com/apt gke-gcloud-auth-plugin main" | sudo tee /etc/apt/sources.list.d/gke-gcloud-auth-plugin.list
        curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
        sudo apt-get update && sudo apt-get install -y gke-gcloud-auth-plugin

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build and Push Docker image
      env:
        IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/graphql-user-service
      run: |
        docker build -t $IMAGE_NAME:$GITHUB_SHA .
        docker push $IMAGE_NAME:$GITHUB_SHA

    - name: Deploy to GKE
      run: |
        gcloud container clusters get-credentials netsjs-cluster --zone us-central1 --project ${{ secrets.GCP_PROJECT_ID }}
        kubectl set image deployment/graphql-user-service graphql-user-service=$IMAGE_NAME:$GITHUB_SHA
